blank_issues_enabled: false
contact_links:
  - name: 💬 WhatsApp Support Group
    url: https://chat.whatsapp.com/D3pfq0vSmwd0iR0dFNjj43
    about: Ask questions or discuss features directly with the community on WhatsApp.
